[package]
name = "kvs"
version = "0.1.0"
authors = ["Sriharsha Mucheli <harshasrisri@gmail.com>"]
edition = "2018"
description = "A key-value store"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
